### ISSUE TITLE
Device provisioning from C8Y to TTN LNS fails

### ISSUE THREAD

**Issue by phcrb** [SoftwareAG/cumulocity-lora#26]
Hi when I setup a device on C8Y side, it does not appear in inventory, and of course is not pushed to ttn
Some java errors in app logs
see attached log file
see screenshot 

Caused by: java.lang.NullPointerException: null
	at lora.ns.DeviceProvisioning.validate(DeviceProvisioning.java:198)
	at lora.ns.LNSIntegrationService.provisionDevice(LNSIntegrationService.java:230)
	at lora.rest.LNSRestController.provisionDevice(LNSRestController.java:62)

**Comment by cpoder** [comment]
Hi,

Sorry, the UI needs to be updated as it should now allow choosing between OTAA and ABP registration.
Defaulting provisioningMode parameter to "OTAA" should resolve this issue.

**Comment by cpoder** [comment]
Should be fixed with current UI version.

**Comment by phcrb** [comment]
Hi here are some more details:
I try to create a new device in c8y, bound to ttn
- name = lora-field-17
- deveui = 0018B20000001437
- appeui = 0018B24441524632
- appkey = C150015DC9CCA58720DB07CFBF9D7EE8
nb: all letters in the keys are uppercased
There is no choice to select ABP or OTAA

the device is not created in cumulocity and no more pushed to ttn

java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: b
see complete log:
[issue26.txt](https://github.com/SoftwareAG/cumulocity-lora/files/6622635/issue26.txt)
![issue26](https://user-images.githubusercontent.com/84912886/121329627-ab473980-c915-11eb-8363-5f3b3ecb3a45.jpg)

**Comment by cpoder** [comment]
Hi,
Internally app key, app EUI and dev EUI are stored in lower case, even if you put them in upper case in the UI... But TTN needs them in upper case.
I updated TTN microservice so it now use upper case values.

**Comment by phcrb** [comment]
checked june-18
creating a device in C8Y 
![image](https://user-images.githubusercontent.com/84912886/122681540-0968fc00-d1f5-11eb-84eb-2d4a40993d53.png)

The device is pushed to ttn 
![image](https://user-images.githubusercontent.com/84912886/122681579-34535000-d1f5-11eb-998d-a0f084aecc49.png)

But it appears to be configured with APB instead of OTAA
The external Join server is checked 
![image](https://user-images.githubusercontent.com/84912886/122681604-6e245680-d1f5-11eb-9699-6d9c439599a2.png)
and the Network Server and Application server addresses are not filled

**Comment by phcrb** [comment]
Hi, there is still an issue
- creating the device from cumulocity:
![image](https://user-images.githubusercontent.com/84912886/124882611-de422300-dfd0-11eb-89d3-5e94e47b1fc1.png)
the device is created in the inventory, and is pushed to ttn
but the network settings in ttn are wrong:
![image](https://user-images.githubusercontent.com/84912886/124882905-1d707400-dfd1-11eb-860b-68e61c733907.png)

Here are the settings that work when setting up a device from ttn:
![image](https://user-images.githubusercontent.com/84912886/124883105-4c86e580-dfd1-11eb-9893-4c95ee189012.png)

**Comment by cpoder** [comment]
This is now fixed with the latest commit.
Additionally it is now possible to configure device provisioning addtional parameters per LNS type.
Example: TTN connectors now have the following addtional parameters when provisioning devices: MAC Version, PHY Version and Frequency Plan.
